// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    S: 1,
    MIN: 60,
    H: 60 * 60,
    D: 60 * 60 * 24,
    W: 60 * 60 * 24 * 7,
    MON: 60 * 60 * 24 * 30,
    Y: 60 * 60 * 24 * 365,
    format_twodigit: function(n) {
      if (n.toString().length < 2) {
        return '0' + n.toString();
      } else {
        return n;
      }
    },
    get_time_string: function(y, mon, w, d, h, min, s) {
      var str;
      str = "-";
      if (y) {
        str += y + "y";
      }
      if (mon) {
        str += mon + "mon";
      }
      if (w) {
        str += w + "w";
      }
      if (d) {
        str += d + "d";
      }
      if (h) {
        str += h + "h";
      }
      if (min) {
        str += min + "min";
      }
      if (s) {
        str += s + "s";
      }
      if (str === '-') {
        str = '-1min';
      }
      return str;
    },
    parse_time: function(time) {
      var d, h, min, mon, s, time_ary, w, y;
      time_ary = /\-?(([0-9]+)y)?(([0-9]+)mon)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)min)?(([0-9]+)s)?/.exec(time);
      y = time_ary[2] || 0;
      mon = time_ary[4] || 0;
      w = time_ary[6] || 0;
      d = time_ary[8] || 0;
      h = time_ary[10] || 0;
      min = time_ary[12] || 0;
      s = time_ary[14] || 0;
      return [y, mon, w, d, h, min, s];
    },
    parse_time_to_i: function(time) {
      var d, h, min, mon, s, seconds, time_ary, w, y;
      time_ary = /\-?(([0-9]+)y)?(([0-9]+)mon)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)min)?(([0-9]+)s)?/.exec(time);
      y = time_ary[2] || 0;
      mon = time_ary[4] || 0;
      w = time_ary[6] || 0;
      d = time_ary[8] || 0;
      h = time_ary[10] || 0;
      min = time_ary[12] || 0;
      s = time_ary[14] || 0;
      seconds = s * S;
      seconds += min * MIN;
      seconds += h * H;
      seconds += d * D;
      seconds += w * W;
      seconds += mon * MON;
      seconds += y * Y;
      return parseInt(seconds);
    },
    seconds_to_time_string: function(seconds) {
      var d, h, min, mon, s, str, w, y;
      str = '-';
      if (seconds > Y) {
        y = parseInt(seconds / Y);
        seconds = seconds - y * Y;
        str += y + "y";
      }
      if (seconds > MON) {
        mon = parseInt(seconds / MON);
        seconds = seconds - mon * MON;
        str += mon + "mon";
      }
      if (seconds > W) {
        w = parseInt(seconds / W);
        seconds = seconds - w * W;
        str += w + "w";
      }
      if (seconds > D) {
        d = parseInt(seconds / D);
        seconds = seconds - d * D;
        str += d + "d";
      }
      if (seconds > H) {
        h = parseInt(seconds / H);
        seconds = seconds - h * H;
        str += h + "h";
      }
      if (seconds > MIN) {
        min = parseInt(seconds / MIN);
        seconds = seconds - min * MIN;
        str += min + "min";
      }
      if (seconds) {
        s = seconds;
        str += s + "s";
      }
      return str;
    },
    colors: ["red", "green", "yellow", "blue", "magenta", "cyan", "white", "lightblack", "lightred", "lightgreen", "lightyellow", "lightblue", "lightmagenta", "lightcyan", "lightwhite"]
  };

}).call(this);
